iter5 rc
MikeRez0/ypmetrics pull request #15
Opened 2024-05-14 07:05 UTC by MikeRez0

Sprint 1 Iteration 5

2024-05-14 09:40 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Поправь `metricstest` и `statictest` как описано здесь: https://app.pachca.com/chats/9180496?message=230119157

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

Обрати внимание на этот тред: https://app.pachca.com/chats/9180496?message=243787071

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +		panic(err)
Не надо паниковать, смотри видео про ошибки: https://app.pachca.com/chats/9180496?message=234290731

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +	for i := 1; ; i++ {
1. Это не очень хорошо выглядит: создай лучше два тикера, по селекту либо собирай метрики, либо отправляй на сервер
2. В `main.go` лежит очень много кода, перенеси логику в `internal`. В `main` должна оставаться только точка входа + начальная конфигурация сервиса

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +	// return nil
deadcode

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +			requestStr += fmt.Sprint(value)
Для конверсии числе в строки используй `strconv`

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +			fmt.Println(requestStr)
Используй `log` вместо `fmt`

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +func report(metricStore *agent.MetricStore, serverURL string) {
Ошибки лучше прокидывать наверх и обрабатывать их на самом верхнем уровне

2024-05-14 09:40 UTC, s-shpak commented on cmd/server/main.go
> +	if envHostString := os.Getenv("ADDRESS"); envHostString != "" {
Лучше используй `https://pkg.go.dev/os#LookupEnv`

2024-05-14 09:40 UTC, s-shpak commented on cmd/agent/main.go
> +	hostString := flag.String("a", `localhost:8080`, "HTTP server endpoint")
Конфигурацию лучше вынести в отдельную функцию

2024-05-14 09:40 UTC, s-shpak commented on go.mod
> +go 1.21.4
```suggestion
go 1.22.3
```

2024-05-14 09:40 UTC, s-shpak commented on internal/agent/agent.go
> +		s := reflect.ValueOf(&memStats).Elem()
Не используй reflect, это дорого. Помещай метрики в хранилище напрямую (да, много кода, к сожалению)

2024-05-14 09:40 UTC, s-shpak commented on internal/agent/metrics.go
> +	Value      any
Тоже дороговато: численные значения будут помещаться на heap. Сделай лучше два отдельных хранилища: для Counter и для Gauge

2024-05-14 09:40 UTC, s-shpak commented on internal/handlers/handlers.go
> +	fmt.Println("Status", http.StatusBadRequest, r.URL)
Ошибки < 500 не надо логировать

2024-05-14 09:40 UTC, s-shpak commented on internal/handlers/handlers.go
> +func (mh *MetricsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
Это же делается gin'ом автоматически ?

2024-05-14 09:40 UTC, s-shpak commented on internal/handlers/html.go
> +	tmpl, err := template.New(tmplFile).ParseFiles(tmplFile)
Не стоит на каждый вызов парсить этот файл. Сделай это один раз. Содержимое файла можно поместить прямо в код (либо использовать пакет `embed`)

2024-05-14 09:40 UTC, s-shpak commented on internal/handlers/html.go
> +		c.AbortWithError(http.StatusInternalServerError, err)
Internal Server Error ошибки надо логировать

2024-05-14 09:40 UTC, s-shpak commented on internal/handlers/metrics.go
> +	matches := UpdateMetricRe.FindStringSubmatch(r.URL.Path)
Gin все это делает за тебя, не надо

2024-05-14 09:40 UTC, s-shpak commented on internal/storage/memstorage.go
> +		}{name, fmt.Sprint(value)})
Используй `strconv` для перевода чисел в строки

2024-05-15 20:50 UTC, MikeRez0 commented on cmd/agent/main.go
> +	// return nil
done

2024-05-15 21:12 UTC, MikeRez0 commented on cmd/agent/main.go
> +		panic(err)
done

2024-05-15 21:13 UTC, MikeRez0 commented on cmd/agent/main.go
> +			requestStr += fmt.Sprint(value)
done

2024-05-15 21:14 UTC, MikeRez0 commented on cmd/agent/main.go
> +			fmt.Println(requestStr)
done

2024-05-15 21:14 UTC, MikeRez0 commented on internal/handlers/handlers.go
> +func (mh *MetricsHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
done

2024-05-15 21:15 UTC, MikeRez0 commented on internal/handlers/metrics.go
> +	matches := UpdateMetricRe.FindStringSubmatch(r.URL.Path)
done

2024-05-15 21:20 UTC, MikeRez0 commented on internal/storage/memstorage.go
> +		}{name, fmt.Sprint(value)})
done

2024-05-15 21:21 UTC, MikeRez0 commented on cmd/server/main.go
> +	if envHostString := os.Getenv("ADDRESS"); envHostString != "" {
done

2024-05-15 21:21 UTC, MikeRez0 commented on cmd/agent/main.go
> +	hostString := flag.String("a", `localhost:8080`, "HTTP server endpoint")
done

2024-05-15 21:22 UTC, MikeRez0 commented on internal/agent/metrics.go
> +	Value      any
done

2024-05-15 21:22 UTC, MikeRez0 commented on internal/handlers/handlers.go
> +	fmt.Println("Status", http.StatusBadRequest, r.URL)
done

2024-05-15 21:44 UTC, MikeRez0 commented on internal/handlers/html.go
> +	tmpl, err := template.New(tmplFile).ParseFiles(tmplFile)
done

2024-05-16 18:58 UTC, MikeRez0 commented on internal/agent/agent.go
> +		s := reflect.ValueOf(&memStats).Elem()
done

2024-05-16 19:19 UTC, MikeRez0 commented on cmd/agent/main.go
> +	for i := 1; ; i++ {
done

2024-05-20 11:16 UTC, s-shpak requested changes

2024-05-20 11:16 UTC, s-shpak commented on .vscode/launch.json
Этот файл обычно не пушится в репозиторий - это локальные настройки среды. которые могут быть индивидуальными для каждого разработчика

2024-05-20 11:16 UTC, s-shpak commented on .vscode/settings.json
Аналогично комментарию выше

2024-05-20 11:16 UTC, s-shpak commented on internal/handlers/html.go
> +	if tmpl == nil {
Лучше дейлай это при инициализации `MetricsHandler` - так ты точно избежишь data-race

2024-05-20 11:16 UTC, s-shpak commented on internal/handlers/html.go
> +			log.Println(err)
В ошибки стоит добавлять больше контекста:


```suggestion
			log.Printf("failed to parse the metrics HTML template: %v", err)
```

2024-05-20 16:07 UTC, MikeRez0 commented on internal/handlers/html.go
> +			log.Println(err)
done

2024-05-20 16:07 UTC, MikeRez0 commented on internal/handlers/html.go
> +	if tmpl == nil {
done

2024-05-20 16:07 UTC, MikeRez0 commented on .vscode/settings.json
done

2024-05-20 16:07 UTC, MikeRez0 commented on .vscode/launch.json
done

2024-05-21 08:07 UTC, s-shpak approved these changes

2024-05-21 08:24 UTC, merged