Iter9
MikeRez0/ypmetrics pull request #19
Opened 2024-05-31 08:55 UTC by MikeRez0

Sprint 2 (iter 9)

2024-06-02 20:40 UTC, s-shpak requested changes

2024-06-02 20:40 UTC, s-shpak commented on .vscode/launch.json
Этот файл как правило не пушится в репозиторий, он остается локальным для каждого разработчика. Не то чтобы это очень важно, но fyi. Коммент можно зарезолвить

2024-06-02 20:40 UTC, s-shpak commented on cmd/server/main.go
> +	// r.Use(handlers.GinCompress())
deadcode

2024-06-02 20:40 UTC, s-shpak commented on internal/handlers/gzip.go
> +				_ = ctx.AbortWithError(http.StatusInternalServerError,
Ошибки, приводящие к `InternalServerError` надо логировать

2024-06-02 20:40 UTC, s-shpak commented on internal/handlers/metrics.go
> +			logger.Log.Error("Error updating metric "+metric.ID, zap.Error(err))
Помести ID метрики в отдельное поле

2024-06-02 20:40 UTC, s-shpak commented on internal/handlers/metrics.go
> +			log.Println(err)
Штатные ошибки не надо логировать

2024-06-02 20:40 UTC, s-shpak commented on internal/handlers/metrics.go
> +			log.Println(err)
Т.к. ты используешь `zap`, используй его везде. Не используй дефолтный пакет `log`

2024-06-02 20:40 UTC, s-shpak commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
Глобальные переменные не нужны. Возвращай логгер из функции инициализации и прокидывай его туда, где он используется

2024-06-02 20:40 UTC, s-shpak commented on internal/logger/logger.go
> +		return fmt.Errorf("%w", err)
Добавляй ошибкам контекст

```suggestion
		return fmt.Errorf("failed to parse the atomic level %s: %w", level, err)
```

2024-06-03 12:52 UTC, MikeRez0 commented on cmd/server/main.go
> +	// r.Use(handlers.GinCompress())
done

2024-06-03 12:53 UTC, MikeRez0 commented on internal/handlers/gzip.go
> +				_ = ctx.AbortWithError(http.StatusInternalServerError,
done

2024-06-03 12:57 UTC, MikeRez0 commented on internal/handlers/metrics.go
> +			logger.Log.Error("Error updating metric "+metric.ID, zap.Error(err))
done

2024-06-03 13:00 UTC, MikeRez0 commented on internal/handlers/metrics.go
> +			log.Println(err)
done

2024-06-03 13:00 UTC, MikeRez0 commented on internal/handlers/metrics.go
> +			log.Println(err)
done

2024-06-03 13:27 UTC, MikeRez0 commented on internal/logger/logger.go
> +		return fmt.Errorf("%w", err)
done

2024-06-03 14:33 UTC, MikeRez0 commented on internal/logger/logger.go
> +var Log *zap.Logger = zap.NewNop()
done

2024-06-03 14:34 UTC, MikeRez0 commented on .vscode/launch.json
в .gitignore добавлен, но не исключается

2024-06-04 11:01 UTC, s-shpak requested changes

2024-06-04 11:01 UTC, s-shpak commented on internal/handlers/metrics.go
> +			logger.Log.Error("error on guage update", zap.Error(err))
Здесь надо возвращаться из функции

2024-06-04 11:01 UTC, s-shpak commented on .vscode/launch.json
надо сделать `git rm`

2024-06-04 11:01 UTC, s-shpak commented on cmd/server/main.go
> +	r.POST("/update/", handlers.GinCompress(mylog), h.UpdateMetricJSON)
Посмотри здесь, как правильнее подключать middleware: https://gin-gonic.com/docs/examples/using-middleware/

2024-06-04 11:01 UTC, s-shpak commented on cmd/server/main.go
> +	h, err := handlers.NewMetricsHandler(repo, mylog)
Если ты помещаешь логгер в разные слои, то хорошей идеей может быть добавление поля в логгер, которое указывает имя компонента, который пишет логи. Что-то типа

```suggestion
	h, err := handlers.NewMetricsHandler(repo, mylog.With(zap.String("component", "handlers")))
```

2024-06-04 11:51 UTC, MikeRez0 commented on internal/handlers/metrics.go
> +			logger.Log.Error("error on guage update", zap.Error(err))
done

2024-06-04 13:14 UTC, MikeRez0 commented on cmd/server/main.go
> +	r.POST("/update/", handlers.GinCompress(mylog), h.UpdateMetricJSON)
done

2024-06-04 14:55 UTC, MikeRez0 commented on cmd/server/main.go
> +	h, err := handlers.NewMetricsHandler(repo, mylog)
done

2024-06-04 15:50 UTC, s-shpak requested changes

2024-06-04 15:50 UTC, s-shpak commented on cmd/server/main.go
> +	jsonGroup.Use(handlers.GinCompress(logger.LoggerWithComponent(mylog, "compress")))
1. Логгер стоит поставить самой внешней middleware, чтобы он логировал запрос до обработки и ответ после
2. Не стоит вкладывать middleware одну в другую - лучше добавить их также, как ты делаешь выше

2024-06-04 19:38 UTC, MikeRez0 commented on cmd/server/main.go
> +	jsonGroup.Use(handlers.GinCompress(logger.LoggerWithComponent(mylog, "compress")))
Сергей, или не понял замечания или не согласен:
1. Логгер в виде middleware подключен в строке 29, сразу после Recovery
2. В строке 40 нет вложенной middleware, это передается логгер в middleware GinCompress (передал logger через замыкание)

2024-06-04 21:53 UTC, s-shpak commented on cmd/server/main.go
> +	jsonGroup.Use(handlers.GinCompress(logger.LoggerWithComponent(mylog, "compress")))
Прошу прощения, неправильно понял

2024-07-09 19:13 UTC, merged